config/routes.rb
Rich::Engine.routes.draw do
  
  resources :files, :controller => "files"
  post '/files/update/:id', to: "files#update"
end

app/models/rich/rich_file.rb
require 'cgi'
require 'mime/types'
require 'kaminari'

module Rich
  class RichFile < ActiveRecord::Base
    scope :files,   -> { where("rich_rich_files.simplified_type  = 'file'") }
    scope :images,  -> { where("rich_rich_files.simplified_type  = 'image'") }
    scope :videos,   -> { where("rich_rich_files.simplified_type = 'video'") }

    paginates_per Rich.options[:paginates_per]

    mount_uploader :rich_file_file_name, RichFileUploader

    before_validation :update_rich_file_attributes

    validate :check_content_type
    validates :rich_file_file_name,
      :presence => true,
      :file_size => {
        :maximum => 15.megabytes.to_i
      }

    after_save :clear_uri_cache
    after_destroy :unlink_from_associations

    delegate :to_s, to: :filename

    def self.associated_models
      Rails.application.eager_load!
      ApplicationRecord.subclasses.select do |constant|
        constant.reflect_on_all_associations(:belongs_to).any? { |ref| ref.options[:class_name] == 'Rich::RichFile' }
      end
    end

    def image_tags
      self.tags
    end

    def image_tags=(val)
      self.tags = val
    end

    def rich_file
      self.rich_file_file_name
    end

    def rich_file=(val)
      self.rich_file_file_name = val
    end

    def filename
      rich_file.file.filename
    end

    def uri_cache
      uri_cache_attribute = read_attribute(:uri_cache)
      if uri_cache_attribute.blank?
        uris = {}

        rich_file.versions.each do |version|
          uris[version[0]] = rich_file.url(version[0].to_sym, false)
        end

        # manualy add the original size
        uris["original"] = rich_file.url

        uri_cache_attribute = uris.to_json
        write_attribute(:uri_cache, uri_cache_attribute)
      end
      uri_cache_attribute
    end

    def fileExt
      rich_file.file.extension
    end

    def nameNoExt
      extension = '.' + rich_file.file.extension
      withoutPath = rich_file.file.filename.gsub( extension, "" )
      withoutPath
    end

    def sizes_available
      image_dimension
      sizeslist = []
      rich_file.versions.keys.each_with_index do |version, idx|
        vvs = version.to_s
        if vvs.include? "x"
          sizeslist.push( vvs.gsub("image_", "") )
        end
      end
      sizeslist
    end

    def image_dimension
      # Rails.logger.info rich_file.file
      dsize = Paperclip::Geometry.from_file(rich_file.file)
      dsize
    end

    def image_dimension_browser
      begin
        dimensions = rich_file.store_dimensions
        img_dims = dimensions.to_s
        img_dims = img_dims.gsub("[", "")
        img_dims = img_dims.gsub("]", "")
        img_dims = img_dims.gsub(", ", "x")
      rescue
        img_dims = ""
      end
      img_dims
    end

    def rename!(new_filename_without_extension)
      new_filename = new_filename_without_extension + '.' + rich_file.file.extension
      rename_files!(new_filename)
      rich_file.model.update_column(:rich_file_file_name, new_filename)
      clear_uri_cache
      new_filename
    end

    private

    def check_content_type
      unless Rich.validate_mime_type(self.rich_file_content_type, self.simplified_type)
        self.errors[:base] << "'#{self.rich_file_file_name}' is not the right type."
      end
    end

    def clear_uri_cache
      write_attribute(:uri_cache, nil)
    end

    def rename_files!(new_filename)
      rename_file!(rich_file, new_filename)
      rich_file.versions.keys.each do |version|
        rename_file!(rich_file.send(version), "#{version}_#{new_filename}")
      end
    end

    def rename_file!(version, new_filename)
      Rails.logger.info "rename_file!"
      Rails.logger.info "version: #{version}"
      Rails.logger.info "new_filename: #{new_filename}"
      if !version.nil?
        path = version.path
        Rails.logger.info "path: #{path}"
        if !path.nil? && !path.empty?
          Rails.logger.info "DO rename_file!"
          Rails.logger.info path
          Rails.logger.info File.dirname(path)
          Rails.logger.info new_filename
          # FileUtils.move path, File.join(File.dirname(path), new_filename)
          File.rename path, File.join(File.dirname(path), new_filename)
        end 
      end
    end

    def unlink_from_associations
      if (matching_reflections = self.class.associated_models).any?
        matching_reflections.map do |constant|
          constant.reflect_on_all_associations(:belongs_to).select { |ref| ref.options[:class_name] == 'Rich::RichFile' }.map do |ref|
            constant.where(ref.options[:foreign_key] => self.id).update_all(ref.options[:foreign_key] => nil)
          end
        end
      end
    end

    def update_rich_file_attributes
      if rich_file.present? && rich_file_file_name_changed?
        self.rich_file_content_type = rich_file.file.content_type
        self.rich_file_file_size = rich_file.file.size
        self.rich_file_updated_at = Time.now
      end
    end

    module ClassMethods

    end

  end
end

app/controllers/rich/application_controller.rb
module Rich
  class ApplicationController < ActionController::Base
    
    before_filter :authenticate_rich_user
    
    def authenticate_rich_user
      send(Rich.authentication_method) unless Rich.authentication_method == :none
    end
    
  end
end

app/controllers/rich/display_controller.rb
module Rich
	class DisplayController < ApplicationController
		def show
			if params[:id]
				file = RichFile.find(params[:id])
				if file.blank?
					render :text => "File not found"
				else
					if params[:style] && file.rich_file.styles.include?(params[:style].to_sym)
						@url = file.rich_file.url(params[:style].to_sym)
					else
						@url = file.rich_file.url
					end
				end

				render :layout => false
			else 
				render :text => "File not found"
			end			
		end
	end
end

app/controllers/rich/files_controller.rb
module Rich
  class FilesController < ApplicationController

    before_action :authenticate_rich_user
    before_action :set_rich_file, only: [:show, :update, :destroy]

    layout "rich/application"

    def index
      @type = params[:type]

      @items = case @type
      when 'file'
        RichFile.files
      when 'image'
        RichFile.images
      when 'video'
        RichFile.videos
      end

      if params[:scoped] == 'true'
        @items = @items.where("owner_type = ? AND owner_id = ?", params[:scope_type], params[:scope_id])
      end

      searchRoute = false
      if params[:search].present?
        # @items = @items.where('rich_file_file_name ILIKE ?', "%#{ params[:search] }%") #original-search
        searchString = params[:search]
        searchString = searchString.strip
        searchList = Array.new
        Rails.logger.info "SEARCH MANY"
        if searchString.include? ","
          searchList_in = searchString.split(",")
          searchList_in.each_with_index do |s, idx|
            s = s.strip
            if !s.empty? 
              searchList.push("%#{s}%")
            end
          end
          Rails.logger.info searchList
          if searchList.length > 0
            @items = @items.where('rich_file_file_name ILIKE ANY ( array[?] )', searchList)
            searchRoute = true
          end
        else
          if !searchString.empty? 
            @items = @items.where('rich_file_file_name ILIKE ?', "%#{ searchString }%")
            searchRoute = true
          end
        end
      end

      if params[:searchtags].present?
        searchString = params[:searchtags]
        searchString = searchString.strip
        searchList = Array.new
        Rails.logger.info "SEARCH MANY TAGS"
        if searchString.include? ","
          searchList_in = searchString.split(",")
          searchList_in.each_with_index do |s, idx|
            s = s.strip
            if !s.empty? 
              searchList.push("%#{s}%")
            end
          end
          Rails.logger.info searchList
          if searchList.length > 0
            @items = @items.where('tags ILIKE ANY ( array[?] )', searchList)
            searchRoute = true
          end
        else
          if !searchString.empty? 
            @items = @items.where('tags ILIKE ?', "%#{ searchString }%")
            searchRoute = true
          end
        end
      end

      if params[:alpha].present?
        @items = @items.order("rich_file_file_name ASC")
      else
        @items = @items.order("created_at DESC")
      end

      if !searchRoute # paginate if ALL files
        @items = @items.page params[:page]
      end

      # stub for new file
      @rich_asset = RichFile.new

      respond_to do |format|
        format.html
        format.js
      end

    end

    def show
      # show is used to retrieve single files through XHR requests after a file has been uploaded

      if(params[:id])
        # list all files
        @file = @rich_file
        render :layout => true
      else
        render :text => "File not found"
      end

    end

    def create
      # use the file from Rack Raw Upload
      file_params = params.fetch(:rich_file, {}).fetch(:rich_file, nil) || (params[:qqfile].is_a?(ActionDispatch::Http::UploadedFile) ? params[:qqfile] : params[:file] )

      # simplified_type is only passed through via JS
      # if using the legacy uploader, we need to determine file type via ActionDispatch::Http::UploadedFile#content_type so the validations on @file do not fail
      sim_file_type = if params[:simplified_type].present?
        params[:simplified_type]
      elsif file_params.content_type =~ /image/i
        'image'
      elsif file_params.content_type =~ /video/i
        'video'
      elsif file_params.content_type =~ /file/i
        'file'
      else
        'file'
      end

      @file = RichFile.new(simplified_type: sim_file_type)

      if(params[:scoped] == 'true')
        @file.owner_type = params[:scope_type]
        @file.owner_id = params[:scope_id].to_i
      end

      if(file_params)
        file_params.content_type = Mime::Type.lookup_by_extension(file_params.try(:original_filename).try(:split, '.').try(:last).try(:to_sym) || params[:file] || params[:qqfile])
        @file.rich_file = file_params
      end

      if @file.save
        response = { success: true, rich_id: @file.id }
      else
        response = { success: false,
                     error: "Could not upload your file:\n- "+@file.errors.to_a[-1].to_s,
                     params: params.inspect }
      end

      render json: response, content_type: "text/html"
    end

    def update
      new_filename_without_extension = ""
      if params[:filename] != nil
        new_filename_without_extension = params[:filename].parameterize
      end     
      if params[:inputfilename] != nil
        new_filename_without_extension = params[:inputfilename]
      end
      tags = params[:image_tags]
      if new_filename_without_extension.present?
        new_filename = @rich_file.rename!(new_filename_without_extension)
        render :json => { :success => true, :filename => new_filename, :uris => @rich_file.uri_cache }
      elsif tags.present?
        @rich_file.tags = tags
        @rich_file.image_tags = tags
        @rich_file.save
        render :json => { :success => true, :image_tags => tags, :uris => @rich_file.uri_cache }
      else
        render :nothing => true, :status => 500
      end
    end

    def destroy
      if(params[:id])
        @rich_file.destroy
        @fileid = params[:id]
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_rich_file
        @rich_file = RichFile.find(params[:id])
      end
  end
end

app/helpers/rich/application_helper.rb
module Rich
  module ApplicationHelper
  end
end

app/helpers/rich/files_helper.rb
module Rich
  module FilesHelper

    def thumb_for_file(file)
      if file.simplified_type == "image"
        file.rich_file.url(:rich_thumb)
      elsif file.simplified_type == "video"
        file.rich_file.url(:video_thumb)
      # elsif file.simplified_type == "file"
      #   file.rich_file.url(:file_thumb)
      else
        asset_path "rich/document-thumb.png"
      end
    end

  end
end

app/views/rich/files/_file.html.erb
<li >
  <div>
     <div>
      <img class="clickable" id="file<%= file.id %>"
            src="<%= thumb_for_file(file) %>"
            data-uris="<%= file.uri_cache %>"
            data-rich-asset-id="<%= file.id %>"
            data-rich-asset-type="<%= file.simplified_type %>"
            data-rich-asset-name="<%= file.filename %>"
      />
      <label> ( <%= file.image_dimension_browser %> ) </label>
      </div>
    <!--%= link_to "delete", "/rich/files/"+file.id.to_s, :method => :delete, :remote => true, :data => { :confirm => t(:delete_confirm) }, :class => "delete", :title => t(:delete) %-->

      <div>
      <!--p data-update-url="<%= file_path(file) %>"
        data-input-placeholder="<%= t('filename_update_input_placeholder') %>"
        title="<%= t('filename_update_hover_hint') %>" id="inputfilename">
        <b><%= file.filename %></b>
      </p-->

      <form accept-charset="UTF-8" action="/rich/files/<%= file.id.to_s %>" data-remote="true" method="put">
        <label name="<%= file.nameNoExt %>"><%= file.filename %></label>
        <input type="text" name="inputfilename" id="inputfilename" value="<%= file.nameNoExt %>" >    
        <input type="submit" value="Rename" name="<%= file.fileExt %>" class="submitfilename">
      </form>
      <form accept-charset="UTF-8" action="/rich/files/<%= file.id.to_s %>" data-remote="true" method="put">
        <label> TAGS: </label>
        <input type="text" name="image_tags" value="<%= file.tags %>" >    
        <input type="submit" value="Add/ Update">
      </form>
      </div>

  </div>
</li>

app/views/rich/files/_filex.html.erb
<li class="clickable" style="margin-bottom:70px;">
  <img  id="file<%= file.id %>"
        src="<%= thumb_for_file(file) %>" 
        data-uris="<%= file.uri_cache %>"
        data-title="<%= file.title %>"
        data-rich-asset-id="<%= file.id %>"
				data-rich-asset-type="<%= file.simplified_type %>"
				data-rich-asset-name="<%= file.rich_file_file_name %>"
  />
  <p><%= file.rich_file_file_name %></p>
  <%= link_to "delete", "/rich/files/"+ file.id.to_s, :method => :delete, :remote => true, :confirm => t(:delete_confirm), :class => "delete", :title => t(:delete) %>
  <%= form_tag("/rich/files/update/" + file.id.to_s , method: 'post', remote: true ) do %>
  	<%= text_field_tag "image-title", file.title, placeholder: "Bildtitel", size: 9 %><span id="saved-<%= file.id %>" style="display:none">Gespeichert!</span>
  	<%= submit_tag "Titel speichern"%>
  <% end %>
</li>

app/views/rich/files/destroy.js.erb
$("#file<%= @fileid %>").parent().remove();

app/views/rich/files/index.html.erb
<header>

  <div id="rich-search">
    <input type="text" placeholder="<%= t('search_bar_placeholder') %> (separate by comma)"/>
  </div>
  <div id="rich-search-tags">
    <input type="text" placeholder="Search by tags (separate by comma)"/>
  </div>

	<div id="loading" style="display:none;"></div>

  <div id="sort-toggle">
    <a href="#" id="sort-by-date" title="<%= t(:sort_by_date_tip) %>"><%= t(:sort_by_date) %></a>
    <a href="#" id="sort-alphabetically" title="<%= t(:sort_alphabetically_tip) %>"><%= t(:sort_alphabetically) %></a>
  </div>

  <!-- ALLOW GRID -->
  <!--div id="view-toggle"> 
    <a href="#" id="view-grid" title="<%= t(:view_grid_tip) %>"><%= t(:view_grid) %></a>
    <a href="#" id="view-list" title="<%= t(:view_list_tip) %>"><%= t(:view_list) %></a>
  </div-->

  <div id="insert-toggle">
    <a href="#" id="insert-many" title="<%= t(:insert_many_tip) %>"><%= t(:insert_many) %></a>
    <a href="#" id="insert-one" title="<%= t(:insert_one_tip) %>"><%= t(:insert_one) %></a>
  </div>

  <ul id="styles" class="scopes">
    <li class="label"><%= t(:available_styles) %></li>
  </ul>

</header>

<div id="legacy-form"><%= form_for(@rich_asset, :url => files_path) do |f| %>
  <p><%= f.file_field :rich_file%></p>
  <%= f.submit("Upload") %>
<% end %>
</div>

<ul id="items" class="list">

  <li id="uploadBlock">
    <div id="upload" class="qq-upload-button placeholder">
      <div class="spinner"></div>
    </div>
    <p><%= t(:upload_a_file) %></p>
  </li>

	<%= render :partial => "file", :collection => @items, :as => :file %>

</ul>

<script>

    function updateLabel(elem) {
        var targetSibling;
	      var sibling = elem.parentNode.firstChild;
        while (sibling) {

          if (sibling.nodeType === 1 && sibling !== elem && sibling.nodeName == "LABEL") {
            targetSibling = sibling;
            break;
          }
          sibling = sibling.nextSibling
        }
        if (targetSibling!=undefined) {
          var targetValue = "";
          // Find value
          sibling = elem.parentNode.firstChild;
          while (sibling) {

            if (sibling.nodeType === 1 && sibling !== elem && sibling.nodeName == "INPUT" && sibling.type == "text") {
              targetValue = sibling.value;
              break;
            }
            sibling = sibling.nextSibling
          }

          targetSibling.innerHTML = targetValue + "." + elem.name ;
        }
   }

    $(document).ready( function() {
      
      var submitfilenames = document.getElementsByClassName("submitfilename");
      console.log("submitfilenames: ", submitfilenames.length);

      if ( submitfilenames.length > 0 ) {
        var i;
        for (i=0; i<submitfilenames.length; i++) {
          var submitfilename = submitfilenames[i];
          submitfilename.addEventListener('click', (event) => {
            //console.log(event);
            console.log(event.target);
            var elem = event.target;
            console.log(elem.parentNode);
            updateLabel(elem);
          })
        }
      }
    });
</script>

app/views/rich/files/index.js.erb
<% if @items.count > 0 %>$("#items").append("<%= escape_javascript(render :partial => "file", :collection => @items, :as => :file) %>");<% end %>

app/views/rich/files/show.html.erb
<%= render :partial => 'file', :locals => {:file => @file} %>

app/views/rich/files/update.js.erb
$("#saved-<%= @file.id %>").css({ display: "block" });
setTimeout(function(){ $("#saved-<%= @file.id %>").css({ display: "none" }); }, 3000);